name: CI Security Pipeline

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write

env:
  NODE_VERSION: '22'

jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci
      - run: npm test

  sast_semgrep:
    name: SAST (Semgrep) + SARIF upload
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten,p/javascript,p/nodejsscan
          generateSarif: true
          output: semgrep.sarif
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }} # optionnel
          # 'strict: true' fait échouer sur findings High; commenter pour éviter l'échec
          strict: true
      - name: Upload Semgrep SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

  sca_npm_audit:
    name: SCA (npm audit)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci
      # Laisse le job passer pour le POC; retirer `|| true` pour fail sur High/Critical
      - run: npx audit-ci --high --report-type full || true

  container_trivy:
    name: Container scan (Trivy)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t app:ci .
      - name: Trivy image scan
        uses: aquasecurity/trivy-action@v0
        with:
          image-ref: 'app:ci'
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          format: 'table'

  dast_zap:
    name: DAST (OWASP ZAP baseline)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t app:ci .
      - name: Run container
        run: docker run -d --name app-ci -p 3000:3000 app:ci
      - name: Wait for app to be ready
        shell: bash
        run: |
          for i in {1..60}; do
            if curl -fsS http://localhost:3000/health >/dev/null; then
              echo "App is up";
              exit 0
            fi
            sleep 1
          done
          echo "App did not start in time"
          docker logs app-ci || true
          exit 1
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:3000'
          cmd_options: '-t 60'
        continue-on-error: true
      - name: Archive ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
      - name: Stop container
        if: always()
        run: docker rm -f app-ci || true
